# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under rrx_mlops_demo/resources/*
# and rrx_mlops_demo/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for rrx-mlops-demo Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./rrx_mlops_demo

env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
  

jobs:
  staging:
    concurrency: rrx-mlops-demo-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.212.2
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging_26
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging_26